

menu = [
    {'item':'family size doritos', 'price': 2.89},
    {'item':'TGIF potato skin', 'price': 2.29},
    {'item':'bugels', 'price': 1.89},
    {'item':'small lays chips', 'price': 0.99},
    {'item':'cheez it', 'price': 3.29},
    {'item':'chex mix', 'price': 1.59,
    {'item':'pringles', 'price': 2.89},
    {'item':'chefs cut jerky', 'price': 6.39},
    {'item':'krave jerky', 'price': 6.39},
    {'item':'lorisa kitchen jerky', 'price': 7.39},
    {'item':'milano cookies', 'price': 3.69},
    {'item':'pepperidge farm pirouette', 'price': 6.49},
    {'item':'pepperidge farm cookies (box)', 'price': 6.99},
    {'item':'goldfish crackers (bag) ', 'price': 2.49},
    {'item':'goldfish crackers (box)', 'price': 9.99},
    {'item':'combox pretzels', 'price': 2.99},
    {'item':'hipz pretzel', 'price': 2.99},
    {'item':'trumoo milk (14 fl oz)', 'price': 1.69},
    {'item':'simply orange juice', 'price': 2.99},
    {'item':'odwalla', 'price': 3.49},
    {'item':'yup', 'price': 2.09},
    {'item':'dasani water (10.1 fl oz)', 'price': 0.99},
    {'item':'dasani water (20 fl oz)', 'price': 1.79},
    {'item':'smart water', 'price': 1.99},
    {'item':'powerade (20oz)', 'price': 1.99},
    {'item':'vitamon water (20oz)', 'price': 1.99},
    {'item':'minute maid', 'price': 1.89},
    {'item':'honest tea', 'price': 2.09},
    {'item':'can pop', 'price': 0.99},
    {'item':'fountain drink (small)', 'price': 1.39},
    {'item':'fountain drink (medium)', 'price': 1.69},
    {'item':'fountain drink (large)', 'price': 1.99},
    {'item':'coke (20oz)', 'price': 1.89}, 
    {'item':'sprite (20oz)', 'price': 1.89},
    {'item':'coke (1L)', 'price': 2.19},
    {'item':'sprite (1L)', 'price': 2.19},
    {'item':'fanta (20oz)', 'price': 1.89},
    {'item':'canada dry ginger ale (20oz)', 'price': 1.89},
    {'item':'fresca', 'price': 1.89},
    {'item':'mello yello', 'price': 1.89},
    {'item':'monster energy', 'price': 3.09},
    {'item':'apple', 'price': 1.19},
    {'item':'mandarin', 'price': 0.49},
    {'item':'asian pear', 'price': 2.69},
    {'item':'chicken & cheese wrap', 'price': 5.99},
    {'item':'grilled vegetables wrap', 'price': 5.99},
    {'item':'chicken caesar salad', 'price': 5.99},
    {'item':'caesar salad', 'price': 5.99},
    {'item':'quinoa & vegetable salad', 'price': 5.99},
    {'item':'classic caesar salad', 'price': 5.99},
    {'item':'garden salad', 'price': 5.99},
    {'item':'greek salad', 'price': 5.99},
    {'item':'chicken salad sandwich', 'price': 5.99},
    {'item':'tuna fish salad sandwich triangle', 'price': 5.99},
    {'item':'smoked turkey + swiss sandwich', 'price': 5.99},
    {'item':'smoked turkey + swiss sandwich', 'price': 5.99},
    {'item':'peanut butter +grape jelly sandwich (white/wheat)', 'price': 2.99},
    {'item':'vegan buffalo wing wrap', 'price': 5.99},
    {'item':'cuban sandwich', 'price': 5.99},
    {'item':'italian combo', 'price': 5.99},
    {'item':'tuna sandwich on gluten free roll', 'price': 5.99},
    {'item':'turkey and swiss sandwich on gluten free roll', 'price': 5.99},
    {'item':'chicken salad sandwich', 'price': 5.99},
    {'item':'chicken with fresh mozzarella + tomato', 'price': 5.99},
    {'item':'tomato,basil,pesto +mozzarella', 'price': 5.99},
    {'item':'tuna salad sandwich', 'price': 5.99},
    {'item':'turkey +cheddar sandwich', 'price': 5.99},
    {'item':'pastrami + swiss sandwich', 'price': 5.99},
    {'item':'corned beef + swiss sandwich', 'price': 5.99},
    {'item':'tuna fish wrap', 'price': 5.99},
    {'item':'roasted beef kaiser sandwich', 'price': 5.99},
    {'item':'tuna salad bites', 'price': 4.99},
    {'item':'buffalo chicken bites', 'price': 4.99},
    {'item':'chicken caesar bites', 'price': 4.99},
    {'item':'tomato +mozzarella bites', 'price': 4.99}]

     
 


